# Generated by Django 5.2.8 on 2026-01-21 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_start_time', models.DateTimeField(blank=True, null=True)),
                ('last_stop_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata_source', models.CharField(blank=True, choices=[('pem', 'Person-Event Metadata'), ('m', 'Person Metadata'), ('', 'Inactive')], default='', max_length=20)),
                ('metadata_key', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path_description', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('allow_duplicate_checkin', models.BooleanField(default=False)),
                ('enforce_checkpoint_order', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('location_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('allow_duplicate_checkin', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoints', to=settings.AUTH_USER_MODEL)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='events.path')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEventMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pems', to='events.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pems', to='people.person')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', through='events.PersonEventMetadata', to='people.person'),
        ),
        migrations.CreateModel(
            name='CheckpointSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_fill', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='events.checkpoint')),
                ('event_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_schemas', to='events.eventschema')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('checkpoint', 'event_schema'), name='unique_checkpoint_schema_when_not_deleted')],
            },
        ),
        migrations.AddIndex(
            model_name='personeventmetadata',
            index=models.Index(fields=['person', 'event'], name='events_pers_person__2ed37f_idx'),
        ),
        migrations.AddIndex(
            model_name='personeventmetadata',
            index=models.Index(fields=['updated_at'], name='events_pers_updated_057c73_idx'),
        ),
        migrations.AddIndex(
            model_name='personeventmetadata',
            index=models.Index(fields=['is_deleted'], name='events_pers_is_dele_c0da06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personeventmetadata',
            unique_together={('person', 'event')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='events_even_is_acti_82811f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='events_even_created_52c227_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_deleted'], name='events_even_is_dele_59021f_idx'),
        ),
    ]
