# Generated by Django 5.2.8 on 2026-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschema',
            name='data_type',
            field=models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('date', 'تاریخ'), ('boolean', 'بولین')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventschema',
            name='metadata_source',
            field=models.CharField(blank=True, choices=[('pem', 'متادیتای شخص-رویداد'), ('m', 'متادیتای شخص'), ('', 'غیرفعال')], default='', max_length=20),
        ),
    ]
