# Generated by Django 5.2.8 on 2026-06-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_safedelete_refactor'),
        ('people', '0002_safedelete_refactor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_single_active_event'),
        ),
    ]
