# Generated by Django 5.2.8 on 2026-01-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_upload_size_mb', models.IntegerField(default=10, verbose_name='حداکثر حجم آپلود (مگابایت)')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
    ]
