# Generated by Django 5.2.8 on 2026-06-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='enable_audio_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='enable_barcode_scanner',
            field=models.BooleanField(default=True),
        ),
    ]
