# Generated by Django 5.2.8 on 2026-06-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings_enable_audio_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='dashboard_event_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='dashboard_event_display_duration',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
