# Generated by Django 5.2.8 on 2026-01-21 21:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField()),
                ('is_approved', models.BooleanField()),
                ('description', models.CharField(blank=True, max_length=400)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='events.checkpoint')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='people.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckInData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(null=True)),
                ('num_value', models.FloatField(null=True)),
                ('bool_value', models.BooleanField(null=True)),
                ('date_value', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='operations.checkin')),
                ('event_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='events.eventschema')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCheckInData',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('text_value', models.TextField(null=True)),
                ('num_value', models.FloatField(null=True)),
                ('bool_value', models.BooleanField(null=True)),
                ('date_value', models.DateField(null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('check_in', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operations.checkin')),
                ('event_schema', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.eventschema')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical check in data',
                'verbose_name_plural': 'historical check in datas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['person', 'checkpoint'], name='operations__person__88f4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['timestamp'], name='operations__timesta_c7e255_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['is_deleted'], name='operations__is_dele_f1cba5_idx'),
        ),
        migrations.AddIndex(
            model_name='checkindata',
            index=models.Index(fields=['event_schema'], name='operations__event_s_f2a38c_idx'),
        ),
        migrations.AddIndex(
            model_name='checkindata',
            index=models.Index(fields=['created_at'], name='operations__created_b564bb_idx'),
        ),
        migrations.AddIndex(
            model_name='checkindata',
            index=models.Index(fields=['is_deleted'], name='operations__is_dele_4ce751_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checkindata',
            unique_together={('check_in', 'event_schema')},
        ),
    ]
