# Generated by Django 5.2.8 on 2026-02-27 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventschema_data_type_and_more'),
        ('operations', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checkin',
            name='operations__is_dele_f1cba5_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkindata',
            name='operations__is_dele_4ce751_idx',
        ),
        migrations.AlterUniqueTogether(
            name='checkindata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='historicalcheckindata',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='checkin',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='checkindata',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='checkindata',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historicalcheckindata',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckindata',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['deleted'], name='operations__deleted_5dbee7_idx'),
        ),
        migrations.AddIndex(
            model_name='checkindata',
            index=models.Index(fields=['deleted'], name='operations__deleted_aa78d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkindata',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('check_in', 'event_schema'), name='unique_active_checkin_data'),
        ),
        migrations.RemoveField(
            model_name='checkindata',
            name='is_deleted',
        ),
    ]
