# Generated by Django 5.2.8 on 2026-06-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_checkin_operations__is_dele_f1cba5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkindata',
            name='bool_value',
        ),
        migrations.RemoveField(
            model_name='checkindata',
            name='date_value',
        ),
        migrations.RemoveField(
            model_name='checkindata',
            name='num_value',
        ),
        migrations.RemoveField(
            model_name='checkindata',
            name='text_value',
        ),
        migrations.RemoveField(
            model_name='historicalcheckindata',
            name='bool_value',
        ),
        migrations.RemoveField(
            model_name='historicalcheckindata',
            name='date_value',
        ),
        migrations.RemoveField(
            model_name='historicalcheckindata',
            name='num_value',
        ),
        migrations.RemoveField(
            model_name='historicalcheckindata',
            name='text_value',
        ),
        migrations.AddField(
            model_name='checkindata',
            name='value',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckindata',
            name='value',
            field=models.JSONField(null=True),
        ),
    ]
