# Generated by Django 5.2.8 on 2026-06-27 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_unique_single_active_event'),
        ('operations', '0003_remove_checkindata_bool_value_and_more'),
        ('people', '0002_safedelete_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['is_valid', 'is_approved'], name='operations__is_vali_302616_idx'),
        ),
    ]
